### ISSUE TITLE
Adding Lint to Your Project

### ISSUE THREAD

**Issue by AlexsandroSA** [Vitao18/build-a-voting-app#1]
Adding Lint to follow some best practices and even catch some errors prior running our code.
 
Some examples:
 - [JavaScript Standard Style](https://standardjs.com/) 
 - [ESLint](https://eslint.org/) 
 - [JSHint](http://jshint.com/)

__Bonus:__ I recommend to use [editorconfig](http://editorconfig.org/) define and maintain consistent coding styles between different editors and IDEs.

**Comment by Vitao18** [comment]
Sup! I don't if there's any guideline with Express/Node in mind. Do you know any?

**Comment by AlexsandroSA** [comment]
For nodejs I usually use the __JavaScript Standard Style__ but if I'm not mistaken it by default does not use the `;`

In that case you can use ESList it's flexibe, it has a nice Arbnb look the [styleguide](https://github.com/airbnb/javascript) and [eslint](https://www.npmjs.com/package/eslint-config-airbnb).

**Comment by Vitao18** [comment]
Sure! I'm familiarized with Airbnb config with React.
Do you mind making the PR to it?

**Comment by AlexsandroSA** [comment]
No problem!

**Comment by Vitao18** [comment]
Thanks!
